NAME = animal
SRC = Animal.cpp Cat.cpp Dog.cpp WrongAnimal.cpp WrongCat.cpp main.cpp
INC = Animal.hpp Cat.hpp Dog.hpp WrongAnimal.hpp WrongCat.hpp
OBJ =



CC = c++
FLAGS = -Wall -Wextra -Werror


all :
	$(CC)  $(SRC) $(FLAGS)  -o $(NAME)


